### ISSUE TITLE
CLIVEONE-W25Q128_STM32H7XX-PB2-PB6-PD11-PD12-PE2-PD13.flm

### ISSUE THREAD

**Issue by ofekAfs** [cturvey/stm32extldr#1]
Hi, can you please create stldr file for the [CLIVEONE-W25Q128_STM32H7XX-PB2-PB6-PD11-PD12-PE2-PD13.flm](https://github.com/cturvey/stm32extldr/blob/main/h7_w25q128/CLIVEONE-W25Q128_STM32H7XX-PB2-PB6-PD11-PD12-PE2-PD13.flm) configuration?

**Comment by cturvey** [comment]
I will check on that this evening. -Clive

**Comment by ofekAfs** [comment]
Thank you very much,

I appreciate it a lot.

**Comment by cturvey** [comment]
Try this
https://github.com/cturvey/stm32extldr/blob/main/h7_w25q128/CLIVEONE-W25Q128_STM32H7XX-PB2-PB6-PD11-PD12-PE2-PD13.stldr
