### ISSUE TITLE
W25Q256J on STM32H750XB

### ISSUE THREAD

**Issue by PirowEC** [cturvey/stm32extldr#9]
Hello,

Not sure if this is possible for you, but I am working with a custom board that requires an external loader for W25Q256J QSPI device on the following pins:
CLK=PF10
CS=PB6
D0=PD11
D1=PD12
D2=PE2
D3=PF6

It would be hugely appreciated.

Thanks

**Comment by cturvey** [comment]
Try
https://github.com/cturvey/stm32extldr/blob/main/h7_w25q256/CLIVEONE-W25Q256_STM32H7XX-PF10-PB6-PD11-PD12-PE2-PF6.stldr

**Comment by PirowEC** [comment]
@cturvey : thank you, I tested it this morning and the external loader is working as expected.

**Comment by cturvey** [comment]
Please consider contributing to the project for time/materials..

  *  https://paypal.me/cliveone (Preferred)
  *  https://www.venmo.com/u/cliveone
  *  https://buymeacoffee.com/cliveone
